# Generated by Django 5.0.6 on 2024-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='responseaudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
